apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-stream-api-nginx-conf
data:
  nginx.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://127.0.0.1:8081;
            proxy_redirect off;
        }
    }
