apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-stream-api-deployment
  labels:
    app: ms-stream-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-stream-api
  template:
    metadata:
      labels:
        app: ms-stream-api
    spec:
      containers:
        - name: ms-stream-api
          image: ms-stream-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: APP_ENV
              value: production
          volumeMounts:
            - mountPath: /go/src/ms-stream-api/assets
              name: video-assets
            - mountPath: /go/src/ms-stream-api/logs
              name: logs
      volumes:
        - name: video-assets
          persistentVolumeClaim:
            claimName: video-assets-pv-claim
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pv-claim
